DROP TABLE IF EXISTS `materialBase`;
DROP TABLE IF EXISTS `material`;
DROP TABLE IF EXISTS `materialSku`;
DROP TABLE IF EXISTS `unit`;
DROP TABLE IF EXISTS `materialUnit`;
DROP TABLE IF EXISTS `materialCategory`;
DROP TABLE IF EXISTS `materialBaseProp`;
DROP TABLE IF EXISTS `materialBasePropVal`;
DROP TABLE IF EXISTS `materialFiles`;
DROP TABLE IF EXISTS `materialCtrlProp`;
DROP TABLE IF EXISTS `materialCtrlPropVal`;
DROP TABLE IF EXISTS `materialCtrlPropValVer`;

CREATE TABLE IF NOT EXISTS `materialBase` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`spuCode` VARCHAR(20) NOT NULL,
	`mnemonic` VARCHAR(20),
	`spuName` VARCHAR(50) NOT NULL,
	`description` VARCHAR(100),
	`type` TINYINT NOT NULL,
	`designCode` VARCHAR(10),
	`designVersion` VARCHAR(10),
	`defaultUnitId` INT UNSIGNED NOT NULL,
	`source` VARCHAR(20),
	`usage` VARCHAR(20),
	`materialCatId` INT UNSIGNED NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `material` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`spuCode` VARCHAR(20) NOT NULL,
	`materialCode` VARCHAR(20) NOT NULL,
	`materialName` VARCHAR(50) NOT NULL,
	`oldMaterialCode` VARCHAR(20),
	`barCode` VARCHAR(20),
	`materialBaseId` INT UNSIGNED NOT NULL,
	`purchasePrice` INT UNSIGNED,
	`sellingPrice` INT UNSIGNED
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `materialSku` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`spuCode` VARCHAR(20) NOT NULL,
	`skuCode` VARCHAR(20) NOT NULL,
	`materialId` INT UNSIGNED NOT NULL,
	`unitId` INT UNSIGNED NOT NULL,
	`purchasePrice` INT UNSIGNED,
	`sellingPrice` INT UNSIGNED
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `unit` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`label` VARCHAR(10) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`englishName` VARCHAR(50) NOT NULL,
	`relatedId` INT UNSIGNED NOT NULL,
	`conversionFactor` DOUBLE NOT NULL,
	`sort` INT UNSIGNED NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `materialUnit` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`spuCode` VARCHAR(20) NOT NULL,
	`unitId` INT UNSIGNED NOT NULL,
	`relatedId` INT UNSIGNED NOT NULL,
	`conversionFactor` DOUBLE NOT NULL,
	`sort` INT UNSIGNED NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `materialCategory` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`code` VARCHAR(20) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`parentId` INT UNSIGNED NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `materialBaseProp` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`materialCatId` INT UNSIGNED NOT NULL,
	`type` TINYINT(4) NOT NULL,
	`label` VARCHAR(10) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`range` VARCHAR(20) NOT NULL,
	`sort` INT UNSIGNED NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `materialBasePropVal` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`spuCode` VARCHAR(20) NOT NULL,
	`materialCode` VARCHAR(20) NOT NULL,
	`materialBasePropId` INT UNSIGNED NOT NULL,
	`value` VARCHAR(10) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `materialFiles` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`materialBaseId` INT UNSIGNED NOT NULL,
	`fileId` INT UNSIGNED NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `materialCtrlProp` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`type` TINYINT(4) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`label` INT UNSIGNED NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `materialCtrlPropVal` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`versionId` INT UNSIGNED NOT NULL,
	`materialCtrlPropId` INT UNSIGNED NOT NULL,
	`value` VARCHAR(10) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `materialCtrlPropValVer` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`version` VARCHAR(10) NOT NULL,
	`origanizationCode` VARCHAR(20) NOT NULL,
	`materialCatId` INT UNSIGNED NOT NULL,
	`materialId` INT UNSIGNED NOT NULL,
	`startDate` DATETIME NOT NULL,
	`endDate` DATETIME NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO materialBase VALUES (null, '10000', '12345', '毛料', '丝绸毛料', 64, '10010000', 'v1.0', 1, '工厂', '纺织', 1);
INSERT INTO materialBase VALUES (null, '10001', '12346', '布料', '尼龙布料', 32, '10020000', 'v1.0', 2, '工厂', '纺织', 2);
INSERT INTO materialBase VALUES (null, '10002', '12347', '棉布', '棉质布料', 16, '10030000', 'v2.0', 3, '工厂', '纺织', 3);